### ISSUE TITLE
커서 모양 변경

### ISSUE THREAD

**Issue by woohm402** [wafflestudio/wafflestudio.com-v3#50]
![image](https://user-images.githubusercontent.com/39977696/159128955-43690901-1d8d-4907-bc48-ac21e86eaae5.png)

pointer 아니면 default 여야 되지 않으려나

**Comment by ars-ki-00** [comment]
아 맞아 까먹ㅇㅆ다 이거 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by ars-ki-00** [comment]
이 정도면 버그 아닌가

**Comment by woohm402** [comment]
원하신다면
